blank_issues_enabled: false
contact_links:
  - name: ğŸš€ Feature Request
    url: https://github.com/Commencement-Technology/react-native-cli-hold-menu/discussions/categories/ideas
    about: Share ideas for new features
  - name: â“ Ask a Question
    url: https://github.com/Commencement-Technology/react-native-cli-hold-menu/discussions/categories/q-a
    about: Ask the community for help